[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "gorder manual"

[preprocessor.katex]
after = ["links"]

[output.html]
input-404 = "not_found.md"
copy-files = ["src/raw.html"]


# [output.pdf]
